version: "3.9"
services:
  hysteria:
    image: ghcr.io/cedar2025/hysteria:latest
    container_name: hy-xz
    restart: always
    network_mode: "host"
    logging:
      driver: "json-file"   #默认的文件日志驱动
      options:
        max-size: "500m"
        max-file: "3"
    volumes:
      - ./server.yaml:/etc/hysteria/server.yaml         # 这里不用改。
      - ./xxx.crt:/etc/hysteria/example.com.crt # 这里不用改。
      - ./xxx.key:/etc/hysteria/example.com.key # 这里不用改。
    command: ["hysteria", "server", "-c", "/etc/hysteria/server.yaml"]
